# ----------------- 考试信息 -----------------
[info]

province = "广东省|GD"
city = "肇庆市|ZQ"
city-code = 441200
name = "初中学业水平考试|中考"  # 考试名称(全称|简称)
date = { start = "2020-07-20", end = "2020-07-22", duration_days = 2 }
local-enrollment = false  # 是否有属地招生机制
score-conversion = true   # 是否有卷面分折算机制

# 各科考试时间
[info.time]
"语文" = { start = "2020-07-20T15:00:00Z", end = "2020-07-20T17:00:00Z", duration = 120 }
"数学" = { start = "2020-07-21T08:30:00Z", end = "2020-07-21T10:00:00Z", duration = 90 }
"道德与法治" = { start = "2020-07-21T10:50:00Z", end = "2020-07-21T11:50:00Z", duration = 60 }
"物理" = { start = "2020-07-21T15:00:00Z", end = "2020-07-21T16:20:00Z", duration = 80 }
"英语" = { start = "2020-07-22T08:30:00Z", end = "2020-07-22T10:00:00Z", duration = 90 }
"化学" = { start = "2020-07-22T10:50:00Z", end = "2020-07-22T11:50:00Z", duration = 60 }
"历史" = { start = "2020-07-22T15:00:00Z", end = "2020-07-22T16:20:00Z", duration = 80 }

# 实际分数
[info.score]
total = 740  # 总分
"语文" = 120  # 各科分数("科目|别名" = 分数)
"数学" = 120
"英语" = 120
"物理" = 100
"历史" = 60
"道德与法治" = 60
"化学" = 100
"体育" = 60

# 考试卷面分(若无该机制删除此项)
[info.score.paper]
"道德与法治" = 100
"历史" = 100

# ----------------- 分数线 -----------------
[cutoff]

# 端州区
[cutoff."端州区|DZ"]
"肇庆宣卿中学|ZQXQZX" = 637.3  # 各学校录取分数线("学校|学校首字母" = 分数线分数)
"肇庆市第一中学|ZQSDYZX" = 613.0
"肇庆市第六中学|ZQSDLZX" = 553.5
"肇庆市端州中学|ZQSDZZX" = 525.1
"肇庆市百花中学|ZQSBHZX" = 470.0
"肇庆学院附属中学|ZQXYFSZX" = 593.0
"肇庆市外语学校|ZQSWYZX" = 593.0
"肇庆市加美学校|ZQSJMXX" = 580.0

# 端州区的分区县计线的学校(score-by-district)
[cutoff."端州区|DZ".sbd]
[cutoff."端州区|DZ".sbd."广东肇庆中学|GDZQZX"]
"端州区|DZ" = 645.4
"鼎湖区|DH" = 646.5
"高要区|GY" = 646.7
"四会市|SH" = 670.0
"广宁县|GN" = 646.6
"德庆县|DQ" = 648.0
"封开县|FK" = 646.2
"怀集县|HJ" = 646.8
"高新区|GX" = 650.3

# 端州区的指标到校政策的学校(quota-based-school)
[cutoff."端州区|DZ".qbs]
"广东肇庆中学|GDZQZX" = 615.4
"肇庆市第一中学|ZQSDYZX" = 583.0
"肇庆市端州中学|ZQSDZZX" = 495.1
notes = [ "广东肇庆中学|GDZQZX 指标到校要求：端州区区域考生要求第一志愿填报广东肇庆中学、综合素质五项（道德品质、英语口语、科学实验操作、信息技术、生物和地理）评价考试至少有两个A级，且道德品质必须B级以上（含B级）；端州区以外考生要求道德品质A级以上（含A级），且第一志愿填报广东肇庆中学" ]

# 鼎湖区
[cutoff."鼎湖区|DH"]
"鼎湖中学|DHZX" = 560.9
"广利高级中学|GLGJZX" = 432.6

# 高要区
[cutoff."高要区|GY"]
"高要一中|GYYZ" = 515.7
"高要二中|GYEZ" = 535.4
"肇庆实验中学|ZQSYZX" = 428.8
"新桥中学|XQZX" = 433.7
[cutoff."高要区|GY".qbs]
"高要一中|GYYZ" = 509.8
"肇庆实验中学|ZQSYZX" = 423.9

# 广宁县
[cutoff."广宁县|GN"]
"广宁中学|GNZX" = 515.0
"广宁县第一中学|GNDYZX" = 410.0
"广宁县钱学森学校|GNXQXSXX" = 366.0
notes = [ "590分以上的优秀学生报读 广宁县钱学森学校|GNXQXSXX ，成绩排名前40名可享受三年学费全免" ]

# 德庆县
[cutoff."德庆县|DQ"]
"香山中学|XSZX" = 452.9
"孔子学校|KZXX" = 357.3
"莫村中学|MCZX" = 353.7
notes = [ "孔子学校|KZXX 艺体类录取分数为353.7，术科分要求60" ]

# 封开县
[cutoff."封开县|FK"]
"广信中学|GXZX" = 539.8
"江口中学|JKZX" = 418.1
"封川中学|FCZX" = 376.3
"南丰中学|NFZX" = 376.3

# 怀集县
[cutoff."怀集县|HJ"]
"怀集中学|HJZX" = 402.0
"怀集一中|HJYZ" = 402.0
"怀集二中|HJEZ" = 382.0
"冷坑中学|LKZX" = 375.0

# 四会市
[cutoff."四会市|SH"]
"四会中学|SHZX" = 548.3
"华侨中学|HQQZX" = 469.1
"北大公学肇庆实验学校|BDGXZQSYXX" = 419.1
notes = [ "四会中学|SHZX 艺体类录取分数为439.1", "华侨中学|HQZX 艺体类录取分数为419.1" ]

# 高新区
[cutoff."高新区|GX"]
"大旺中学|DWZX" = 498.4
"肇庆中学大旺实验学校|ZQZXDWSYXX" = 622.0
[cutoff."高新区|GX".qbs]
"大旺中学|DWZX" = 468.4
notes = [ "大旺中学|DWZX 艺体类录取分数为340，术科分要求为美术82、音乐64、书法82、体育分要求为田径66、武术90、健美操72", "高新区|GX 是位于 四会市|SH 的一个产业开发区，不是传统意义的行政区划" ]
